### ISSUE TITLE
Schema 

### ISSUE THREAD

**Issue by AdamYLiang** [WillHops01/HangOut#3]
**General**
- [x] Add timestamps to tables 
- [x] Consider having a join table between users and events. This is a design choice so up to you, make sure to be able to justify having or not having this. 

**Users**
- [x] Consider holding onto an email since that is different from username 
- [x] Consider holding onto `latitude` and `longitude` for location APIs 

**Members**
- [x] Needs a primary ID. 

**Groups**
- [x] Needs reference to user/creator of group 
- [x] Should hold onto `latitude` and `longitude` for location APIs
- [ ] Consider having a boolean flag to show if group is private or not 

**Events**
- [x] Should have reference to creator 
- [x] Should have start/end time 
- [x] Should have `latitude` and `longitude` for location API 

Let me know if you have any questions about these changes.

**Comment by WillHops01** [comment]
About the users - events joins table.. My plan was to associate users to their events through their group association (events have foriegn key pointing to group).

I only need to be able to pull events for a specific group, or events for a specific user, I think this should work let me know if I am wrong thinking that
