### ISSUE TITLE
User Auth MVP 

### ISSUE THREAD

**Issue by AdamYLiang** [WillHops01/HangOut#6]
**Functionality**
- [x] Signup functionality does not work on Heroku, returning 401(`Invalid email/password combination`) in console. 
- [x] Login page should be a form and signup can stay as a modal prompt for either `demo user` or bringing them to form for sign up session form.  
- [ ] Modal should close when clicking outside of modal 
- [x] Session modal should not say `Log In` on both sign up and log in
- [x] Drop down should exist for logging user out. 

**CSS**
- [ ] Modal should persist when scrolling down the page.
- [x] Video should stretch and fill page.
- [x] Session form buttons should have border radius. 
- [x] General styling along padding/margin/font-size should match original site. Use the inspector and match up with the sizing and pixels. We want to aim for pixel perfection. 

Let me know if you have any questions about this!

**Comment by AdamYLiang** [comment]
- [ ] Video should be flush against the top of the page. 
- [ ] `Hangout` logo in top left should be clickable and routes to index/main page. 
- [ ] Dropdown should be slightly bigger to match original app. 
- [ ] Text for log in form should be aligned to the left.

**Comment by WillHops01** [comment]
for your dropdown comment, when you say bigger do you mean wider or taller? I want to load a user's first 3 groups and show them on the left side (like on the actual site), so once this is ready it will be taller to include this content.

**Comment by WillHops01** [comment]
I have the above changes and re-pushed to Heroku!

**Comment by AdamYLiang** [comment]
Nicely done! One last change:
- [ ] Clicking on Hangout logo routes you to login page when logged in. It should route you to the splash page instead. 
- [ ] Consider `/signup` and `/login` routes when logged in should route to `/find` instead of the root.

**Comment by WillHops01** [comment]
"Clicking on Hangout logo routes you to login page when logged in. It should route you to the splash page instead."

on Heroku for me, when logged in the logo routes to /find. How are you getting to the login page when already logged in?

**Comment by WillHops01** [comment]
Oh do you mean when you manually type "/login" into the url bar?

**Comment by AdamYLiang** [comment]
Indeed, when you manually type in `/login` or `/signup`.

**Comment by WillHops01** [comment]
Ok the changes have been made and pushed to Heroku!

**Comment by AdamYLiang** [comment]
Looks good, nice work!
